no message

diff --git a/syncdb b/syncdb
--- a/syncdb
+++ b/syncdb
@@ -2,7 +2,7 @@
 
 # ***********************************************
 #
-# syncDB v0.2.3
+# syncDB v0.2.4
 # by JP Lew (jplew.com)
 #
 # ***********************************************
@@ -149,7 +149,7 @@ now=$(date +"%y%m%d-%H%M")
 # Search-Replace-DB
 searchScriptName=srdb.class.php
 cliScriptName=srdb.cli.php
-srdbPath=https://raw.github.com/interconnectit/Search-Replace-DB/master/
+srdbPath=https://raw.githubusercontent.com/interconnectit/Search-Replace-DB/master/
 searchScriptPath=$srdbPath$searchScriptName
 cliScriptPath=$srdbPath$cliScriptName
 
@@ -170,8 +170,8 @@ cat <<EOF
     ${blue}SyncDB List of Commands$reset
 
     • backup_local_db
-    • do_login_backup
-    • do_remote_operations
+    • do_remote_bacup
+    • do_remote_replace
     • do_search_replace_remote
     • download_remote_db
     • push
@@ -257,15 +257,14 @@ get_local_db_details () {
     if [[ $number_of_environments < 2 ]]
     then
         return_local_standard
-    else
+    elif [[ ${local_chosen-} != "true" ]]
+    then
         return_nonstandard local
     fi
 
     #Local paths
     l_bak_name1=$now-$l_db_name.mssql
     l_bak_path1=$l_site_dir/$l_bak_dir/$l_bak_name1
-
-    echo
 
 }
 
@@ -299,10 +298,10 @@ return_nonstandard () {
 
     #grep the config file for all relevants hits, and saves them to their
     #respective category. All hits are delimited by spaces.
-    l_db_name=$(sed -n "s/.*DB_NAME',\s*'\([^']*\)'.*/\1/p" $local_config_file)
-    l_db_user=$(sed -n "s/.*DB_USER',\s*'\([^']*\)'.*/\1/p" $local_config_file)
-    l_db_pass=$(sed -n "s/.*DB_PASSWORD',\s*'\([^']*\)'.*/\1/p" $local_config_file)
-    l_db_host=$(sed -n "s/.*DB_HOST',\s*'\([^']*\)'.*/\1/p" $local_config_file)
+    l_db_name=$(sed -n "s/.*DB_NAME', '\([^']*\)'.*/\1/p" $local_config_file)
+    l_db_user=$(sed -n "s/.*DB_USER', '\([^']*\)'.*/\1/p" $local_config_file)
+    l_db_pass=$(sed -n "s/.*DB_PASSWORD', '\([^']*\)'.*/\1/p" $local_config_file)
+    l_db_host=$(sed -n "s/.*DB_HOST', '\([^']*\)'.*/\1/p" $local_config_file)
 
     #This splits the previous values into arrays
     name_array=(${l_db_name// / })
@@ -316,14 +315,16 @@ return_nonstandard () {
     for (( i = 0 ; i < $number_of_environments ; i++ )) 
     do
 
-        if [ ! -n "${host_array[$i]-}" ]
+        #when -u is set for bash, one valid way to test the existence of a
+        #variable, without getting an "unbound variable" error, is to set the
+        #default value to empty like this ${variable-}
+        if [ -z "${host_array[$i]-}" ]
         then
-            PHP_OUT=`php -r 'echo $_ENV{DATABASE_SERVER};'`
-            if [[ $PHP_OUT ]] 
+            db_host=${DATABASE_SERVER:=unset}
+
+            if [[ $db_host ]] 
             then
-                host_array[$i]=$PHP_OUT
-            else
-                host_array[$i]="unset"
+                host_array[$i]=$db_host
             fi
         fi
 
@@ -364,7 +365,9 @@ return_nonstandard () {
             #have to consider it.
             unset env_array[$local_env]
 
-            if [ "$i" -ne "$local_env" ]
+            #don't print the local details, and if we're remote, we only need to
+            #output these once, when the correct remote settings are selected
+            if [[ "$i" -ne "$local_env" ]]
             then
 
                 #Display the title, "Environment #x", only once, on the first
@@ -403,23 +406,25 @@ return_nonstandard () {
     l_db_pass=${!local_env_ref_2}
     l_db_host=${!local_env_ref_3}
 
-    #echo
+    local_chosen=true
+
     #echo "============================================================" 
     #echo " LOCAL DATABASE DETAILS" 
     #echo "============================================================" 
     #echo
 
-    #echo "local DB_USER is:       $l_db_user"
     #echo "local DB_NAME is:       $l_db_name"
+    #echo "local DB_USER is:       $l_db_user"
     #echo "local DB_PASSWORD is:   $l_db_pass"
     #echo "local DB_HOST is:       $l_db_host"
     #echo
 
     #Only prompt the user to pick the remote server if this function has been
     #passed with the "remote" parameter set
-    if [ $parameter == "remote" ]
+    if [[ $parameter == "remote" ]]
     then
 
+        echo
         #Now that we've narrowed down the possibilities of what might be a remote
         #server, prompt the user to pick which one to synchronize
         echo "Synchronize with which remote server?"
@@ -455,12 +460,14 @@ return_nonstandard () {
             echo "remote DB_HOST is:       $r_db_host"
 
             echo
+            # a flag which indicates whether the user has selected a remote environment already. This is so it doesn't pester the user repeatedly with this request.
+            remote_chosen=true
             break
 
         done
 
-    fi
     echo
+    fi
 }
 
 # ---------------------------------------------------------
@@ -472,11 +479,10 @@ return_nonstandard () {
 return_local_standard () {
 
     #grep the config file for the MySQL login details
-    l_db_name=$(sed -n "s/.*DB_NAME',\s*'\([^']*\)'.*/\1/p" $local_config_file)
-    l_db_user=$(sed -n "s/.*DB_USER',\s*'\([^']*\)'.*/\1/p" $local_config_file)
-    l_db_pass=$(sed -n "s/.*DB_PASSWORD',\s*'\([^']*\)'.*/\1/p" $local_config_file)
-    l_db_host=$(sed -n "s/.*DB_HOST',\s*'\([^']*\)'.*/\1/p" $local_config_file)
-
+    l_db_name=$(sed -n "s/.*DB_NAME', '\([^']*\)'.*/\1/p" $local_config_file)
+    l_db_user=$(sed -n "s/.*DB_USER', '\([^']*\)'.*/\1/p" $local_config_file)
+    l_db_pass=$(sed -n "s/.*DB_PASSWORD', '\([^']*\)'.*/\1/p" $local_config_file)
+    l_db_host=$(sed -n "s/.*DB_HOST', '\([^']*\)'.*/\1/p" $local_config_file)
 }
 
 # ---------------------------------------------------------
@@ -487,10 +493,10 @@ return_local_standard () {
 return_remote_standard () {
 
     #grep the config file for the MySQL login details
-    r_db_name=$(sed -n "s/.*DB_NAME',\s*'\([^']*\)'.*/\1/p" wp-config.php)
-    r_db_user=$(sed -n "s/.*DB_USER',\s*'\([^']*\)'.*/\1/p" wp-config.php)
-    r_db_pass=$(sed -n "s/.*DB_PASSWORD',\s*'\([^']*\)'.*/\1/p" wp-config.php)
-    r_db_host=$(sed -n "s/.*DB_HOST',\s*'\([^']*\)'.*/\1/p" wp-config.php)
+    r_db_name=$(sed -n "s/.*DB_NAME', '\([^']*\)'.*/\1/p" wp-config.php)
+    r_db_user=$(sed -n "s/.*DB_USER', '\([^']*\)'.*/\1/p" wp-config.php)
+    r_db_pass=$(sed -n "s/.*DB_PASSWORD', '\([^']*\)'.*/\1/p" wp-config.php)
+    r_db_host=$(sed -n "s/.*DB_HOST', '\([^']*\)'.*/\1/p" wp-config.php)
 
 }
 
@@ -530,7 +536,8 @@ get_remote_db_details () {
     if [[ $number_of_environments < 2 ]]
     then
         return_remote_standard
-    else
+    elif [[ ${remote_chosen-} != "true" ]]
+    then
         return_nonstandard remote
     fi
 
@@ -712,7 +719,7 @@ do_check_for_dirs () {
 
     echo "Checking for existence of remote directories..."
 
-    ssh -q "$ssh_port""$r_user"@"$r_host" "if [[ ! -d "$r_web_dir" ]]; then echo "Remote directory does not exist: $r_web_dir"; exit 1; fi; cd "$r_web_dir"; if [[ ! -d "$r_bak_dir" ]]; then mkdir "$r_bak_dir"; fi;" 
+    ssh -q ${ssh_port}"$r_user"@"$r_host" "if [[ ! -d "$r_web_dir" ]]; then echo "Remote directory does not exist: $r_web_dir"; exit 1; fi; cd "$r_web_dir"; if [[ ! -d "$r_bak_dir" ]]; then mkdir "$r_bak_dir"; fi;" 
 
     checked=true
 }
@@ -739,7 +746,7 @@ upload_script () {
     then
         echo "scp $scp_port./$(basename $0) $r_user@$r_host:~/$r_web_dir/"
         echo
-        scp "$scp_port"./$(basename $0) $r_user@$r_host:~/$r_web_dir/
+        scp ${scp_port}./$(basename $0) $r_user@$r_host:~/$r_web_dir/
         echo
         echo "$green$msgSuccess$reset SyncDB script uploaded to: $r_web_dir/$(basename $0) (your local version was more recent)."
     else
@@ -753,16 +760,16 @@ upload_script () {
 
 
 # ---------------------------------------------------------
-# do_login_backup ()
+# do_remote_bacup ()
 # Login to the remote server via SSH and call backup_remote_db(). Meant to be
 # run locally.
 # ---------------------------------------------------------
-do_login_backup () {
+do_remote_bacup () {
 
     [[ "$checked" ]] || do_check_for_dirs
 
     echo "ssh -t $ssh_port$r_user@$r_host cd $r_web_dir; chmod +x $(basename $0); ./$(basename $0) backup_remote_db;"
-    ssh -t $ssh_port$r_user@$r_host "cd $r_web_dir; ./$(basename $0) backup_remote_db;"
+    ssh -t $ssh_port$r_user@$r_host "cd $r_web_dir; if [ ! -f .bashrc -a -f /etc/profile ]; then . /etc/profile; fi; ./$(basename $0) backup_remote_db;"
 
 }
 
@@ -783,7 +790,7 @@ upload_local_db () {
     if [[ -f "${l_bak_path2}.bz2" ]]
     then
         echo "scp $scp_port${l_bak_path2}.bz2 $r_user@$r_host:~/$r_web_dir/$r_bak_dir"
-        scp "$scp_port"${l_bak_path2}.bz2 $r_user@$r_host:~/$r_web_dir/$r_bak_dir
+        scp ${scp_port}${l_bak_path2}.bz2 $r_user@$r_host:~/$r_web_dir/$r_bak_dir
     else
         echo "$red$msgError$reset Could not locate the local dump file at $(pwd)/${l_bak_name2}.bz2."
         echo
@@ -791,8 +798,10 @@ upload_local_db () {
     fi
 
     echo
+
+    #test whether the file was actually uploaded or not
     echo "if ssh $ssh_port$r_user@$r_host test -e $r_web_dir/$r_bak_dir/${l_bak_name2}.bz2" 
-    if ssh "$ssh_port""$r_user"@"$r_host" test -e "$r_web_dir"/"$r_bak_dir"/${l_bak_name2}.bz2 
+    if ssh ${ssh_port}"$r_user"@"$r_host" test -e "$r_web_dir"/"$r_bak_dir"/${l_bak_name2}.bz2 
     then
         echo
         echo "$green$msgSuccess$reset Dump file uploaded to: $r_web_dir/$r_bak_dir/${l_bak_name2}.bz2"
@@ -802,6 +811,7 @@ upload_local_db () {
         exit 1
     fi
     echo
+
 
 }
 
@@ -880,7 +890,7 @@ replace_remote_db () {
     then
 
         # do this if the standard `drop database` command is available
-        mysql -u$r_db_user -p$r_db_pass -h $r_db_host --show-warnings -Bs<<EOF
+        mysql -u$r_db_user -p$r_db_pass -h $r_db_host --show-warnings -Bs<<EOF >/dev/null 2>&1
         create database if not exists $r_db_name;
         drop database $r_db_name;
         create database $r_db_name;
@@ -888,7 +898,7 @@ EOF
 
     else
         # otherwise do this if `drop database` is not available
-        sql_show="show databases; create database if not exists $r_db_name;"
+        sql_show="show databases; create database if not exists $r_db_name >/dev/null 2>&1;"
 
         echo "mysql -u$r_db_user -p$r_db_pass -h $r_db_host --show-warnings -Bse $sql_show"
 
@@ -960,13 +970,13 @@ install_search_scripts () {
         if [ -f "$searchScriptName" -a -f "$cliScriptName" ]
         then
             echo
-            echo "${green}$msgSuccess$reset $searchScriptName and $cliScriptName downloaded to $r_site_dir/$r_bak_dir/"
+            echo "${green}$msgSuccess$reset $searchScriptName and $cliScriptName downloaded to $(pwd)."
             echo "chmod a+x $searchScriptName $cliScriptName"
             chmod a+x $searchScriptName $cliScriptName
         else
             echo
             echo
-            echo >&2 "${red}$msgError$reset Search and Replace Tool download failed."
+            echo >&2 "${red}$msgError$reset Search and Replace Tool download failed. Could not find $searchScriptName and $cliScriptName in $(pwd). Exiting."
             exit 1
         fi
     fi
@@ -1011,7 +1021,7 @@ search_replace_local () {
 do_search_replace_remote () {
     [[ "$checked" ]] || do_check_for_dirs
 
-    ssh $ssh_port$r_user@$r_host "cd $r_web_dir; ./$(basename $0) search_replace_remote;"
+    ssh $ssh_port$r_user@$r_host "cd $r_web_dir; if [ ! -f .bashrc -a -f /etc/profile ]; then . /etc/profile; fi; ./$(basename $0) search_replace_remote;"
 }
 
 # ---------------------------------------------------------
@@ -1065,14 +1075,14 @@ search_replace_remote () {
 }
 
 # ---------------------------------------------------------
-# do_remote_operations ()
+# do_remote_replace ()
 # Login to remote server and execute replace_remote_db() method.
 # ---------------------------------------------------------
-do_remote_operations () {
+do_remote_replace () {
 
     [[ "$checked" ]] || do_check_for_dirs
 
-    ssh $ssh_port$r_user@$r_host "cd $r_web_dir; ./$(basename $0) replace_remote_db;"
+    ssh $ssh_port$r_user@$r_host "cd $r_web_dir; if [ ! -f .bashrc -a -f /etc/profile ]; then . /etc/profile; fi; ./$(basename $0) replace_remote_db;"
 
 }
 
@@ -1127,9 +1137,9 @@ push () {
 
     upload_script
 
-    do_login_backup
+    do_remote_bacup
 
-    do_remote_operations
+    do_remote_replace
 
     do_search_replace_remote
 
@@ -1151,7 +1161,7 @@ pull () {
 
     upload_script
 
-    do_login_backup
+    do_remote_bacup
 
     download_remote_db
 
@@ -1173,14 +1183,14 @@ pull () {
 # ====================================
 
 echo
-echo "${blue}SyncDB v0.2.2$reset > $yellow${@:-push}$reset"
+echo "${blue}SyncDB v0.2.4$reset > $yellow${@:-push}$reset"
 echo
 
 # if an argument is passed (the number of arguments is not equal to zero), then check if that command is valid or not.
 if [ $# -ne 0 ]
 then
     # place all the command names in an array
-    declare -a list_of_methods=(help get_local_db_details get_remote_db_details download_remote_db backup_local_db backup_remote_db replace_remote_db search_replace_remote push pull replace_local_db search_replace_local rsync_pull say_goodbye do_remote_operations do_search_replace_remote rsync_push do_login_backup upload_script test_ssh)
+    declare -a list_of_methods=(help upload_local_db get_local_db_details get_remote_db_details download_remote_db backup_local_db backup_remote_db replace_remote_db search_replace_remote push pull replace_local_db search_replace_local rsync_pull say_goodbye do_remote_replace do_search_replace_remote rsync_push do_remote_bacup upload_script test_ssh)
 
     # function to check if an item exists in an array
     contains_element () {
